-- CreateTable
CREATE TABLE "Farmer" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "NAME" TEXT NOT NULL,
    "MOBILENUMBER" TEXT NOT NULL,
    "PASSWORDHASH" TEXT NOT NULL,
    "VILLAGE" TEXT NOT NULL,
    "DISTRICT" TEXT NOT NULL,
    "LANDVALUE" REAL NOT NULL,
    "LANDUNIT" TEXT NOT NULL,
    "CROPCATEGORIES" TEXT NOT NULL,
    "REGISTEREDAT" DATETIME NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Farmer_MOBILENUMBER_key" ON "Farmer"("MOBILENUMBER");
